apiVersion: v1
kind: Pod
metadata:
  name: auth
  labels:
    app: auth
spec:
  containers:
    - name: auth
      image: marcelounivalle/msvc_auth:1.0.0
      ports:
        - containerPort: 8000
      env:
        - name: DATABASE_URL
          value: postgresql://login_as_user:hdc5GgXhPdBHos2pTia0BfVJUnNFBNCH@dpg-cpie1da1hbls73bge5a0-a.oregon-postgres.render.com/login_as
        - name: SECRET_KEY_TOKEN
          value: 7gkgXucjwNlPYwACkw2npnSccPvXB0BY

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: auth
